apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-java-quarkus-koowyceh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-java-quarkus-koowyceh 
  name: backend-tests-java-quarkus-koowyceh
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backend-tests-java-quarkus-koowyceh
    weight: 100 
